# Site settings
title: "%%30%30"
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  3030 Game: Don't touch the trees! (Thanks, Chrome dev team!)
baseurl: "/3030"
url: "http://szhu.github.io/3030/"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
